version: '3'

services:
        coursematerial:
                image: ddeeh/docker-hy
                ports:
                        - 4000:80
                container_name: courematerial
        watchtower:
                image: containrrr/watchtower
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                container_name: watchtower

